import { Reveal } from './Reveal.jsx';

function PageHero({ eyebrow, title, copy, action, aside }) {
  return <section className="page-hero"><div className="page-shell page-hero-grid"><Reveal><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p><a className="page-button" href={action.href}>{action.label} <span>→</span></a></Reveal><Reveal delay={90} className="page-hero-aside">{aside}</Reveal></div></section>;
}

export function AboutPage() {
  const things = ['Discover nearby events and activities', 'Explore local businesses and services', 'Create and manage events', 'Share photos and videos', 'Connect with communities and users', 'Receive real-time updates and notifications', 'Promote businesses and offerings'];
  const features = [['Event Discovery', 'Find events based on your interests and location.'], ['Business Promotion', 'Businesses can showcase their services, products, offers, and events to a wider audience.'], ['Content Sharing', 'Users can upload and share photos, videos, and updates with the community.'], ['Personalized Experience', 'Receive recommendations and content relevant to your interests and location.'], ['Secure Authentication', 'Sign in securely using supported authentication methods, including Google Sign-In.']];
  return <><PageHero eyebrow="ABOUT ADDON" title={<>Your city has more.<br/><em>We help you find it.</em></>} copy="AddOn brings neighbourhood discovery, local businesses and memorable experiences together in one useful everyday app." action={{ href: '#events', label: 'Explore events' }} aside={<div className="about-mark"><div>+</div><b>Local is<br/>everything.</b><span>Built for the moments around you.</span></div>} />
    <section className="page-section"><div className="page-shell"><div className="page-heading"><div><p className="eyebrow">ABOUT ADDON</p><h2>A single platform to explore and interact.</h2></div></div><article className="privacy-article"><p className="privacy-intro">AddOn is an innovative social and event discovery platform developed by RockChain Technologies. The platform is designed to connect people, businesses, creators, and event organizers through a seamless digital experience.</p><p>With AddOn, users can discover local events, explore businesses, share content, connect with communities, and stay updated on activities happening around them. Whether you're looking for entertainment, networking opportunities, business promotions, or community engagement, AddOn provides a single platform to explore and interact.</p><h2>Our Mission</h2><p>Our mission is to simplify the way people discover events, businesses, and opportunities by creating a connected ecosystem that brings communities together.</p><h2>What You Can Do With AddOn</h2><ul>{things.map((item) => <li key={item}>{item}</li>)}</ul><h2>Key Features</h2>{features.map(([title, copy]) => <div key={title}><h3>{title}</h3><p>{copy}</p></div>)}</article></div></section>
    <section className="page-section soft-section"><div className="page-shell"><div className="page-heading"><div><p className="eyebrow">OUR COMMITMENT</p><h2>Privacy, reliability, and transparency.</h2></div></div><article className="privacy-article"><p className="privacy-intro">At AddOn, we are committed to providing a secure, reliable, and user-friendly platform while respecting user privacy and maintaining transparency in how data is handled.</p><h2>Developed By</h2><p><strong>RockChain Technologies</strong></p><p>Website: <a href="https://addon.rockchain.in/" target="_blank" rel="noreferrer">addon.rockchain.in</a></p><p>Email: <a href="mailto:contact@rockchain.in">contact@rockchain.in</a></p><h2>Contact Us</h2><div className="privacy-contact-card"><p>For support, feedback, partnerships, or business inquiries, please contact us at:</p><p><strong>Email:</strong> <a href="mailto:contact@rockchain.in">contact@rockchain.in</a></p><p><strong>Website:</strong> <a href="https://addon.rockchain.in/" target="_blank" rel="noreferrer">addon.rockchain.in</a></p></div></article></div></section></>;
}